export const contacts = [
  {
    id: 1,
    name: "Oliver Smith",
    role: "Engineer",
    email: "oliver.smith@bigbinary.com",
    createdAt: "Feb 5,2021",
  },
  {
    id: 2,
    name: "Oliver Smith",
    role: "Engineer",
    email: "oliver.smith@bigbinary.com",
    createdAt: "Feb 5,2021",
  },
  {
    id: 3,
    name: "Oliver Smith",
    role: "Engineer",
    email: "oliver.smith@bigbinary.com",
    createdAt: "Feb 5,2021",
  },
  {
    id: 4,
    name: "Oliver Smith",
    role: "Engineer",
    email: "oliver.smith@bigbinary.com",
    createdAt: "Feb 5,2021",
  },
  {
    id: 5,
    name: "Oliver Smith",
    role: "Engineer",
    email: "oliver.smith@bigbinary.com",
    createdAt: "Feb 5,2021",
  },
  {
    id: 6,
    name: "Oliver Smith",
    role: "Engineer",
    email: "oliver.smith@bigbinary.com",
    createdAt: "Feb 5,2021",
  },
  {
    id: 7,
    name: "Oliver Smith",
    role: "Engineer",
    email: "oliver.smith@bigbinary.com",
    createdAt: "Feb 5,2021",
  },
  {
    id: 8,
    name: "Oliver Smith",
    role: "Engineer",
    email: "oliver.smith@bigbinary.com",
    createdAt: "Feb 5,2021",
  },
  {
    id: 9,
    name: "Oliver Smith",
    role: "Engineer",
    email: "oliver.smith@bigbinary.com",
    createdAt: "Feb 5,2021",
  },
  {
    id: 10,
    name: "Oliver Smith",
    role: "Engineer",
    email: "oliver.smith@bigbinary.com",
    createdAt: "Feb 5,2021",
  },
  {
    id: 11,
    name: "Oliver Smith",
    role: "Engineer",
    email: "oliver.smith@bigbinary.com",
    createdAt: "Feb 5,2021",
  },
  {
    id: 12,
    name: "Oliver Smith",
    role: "Engineer",
    email: "oliver.smith@bigbinary.com",
    createdAt: "Feb 5,2021",
  },
  {
    id: 13,
    name: "Oliver Smith",
    role: "Engineer",
    email: "oliver.smith@bigbinary.com",
    createdAt: "Feb 5,2021",
  },
  {
    id: 14,
    name: "Oliver Smith",
    role: "Engineer",
    email: "oliver.smith@bigbinary.com",
    createdAt: "Feb 5,2021",
  },
  {
    id: 15,
    name: "Oliver Smith",
    role: "Engineer",
    email: "oliver.smith@bigbinary.com",
    createdAt: "Feb 5,2021",
  },
  {
    id: 16,
    name: "Oliver Smith",
    role: "Engineer",
    email: "oliver.smith@bigbinary.com",
    createdAt: "Feb 5,2021",
  },
  {
    id: 17,
    name: "Oliver Smith",
    role: "Engineer",
    email: "oliver.smith@bigbinary.com",
    createdAt: "Feb 5,2021",
  },
  {
    id: 18,
    name: "Oliver Smith",
    role: "Engineer",
    email: "oliver.smith@bigbinary.com",
    createdAt: "Feb 5,2021",
  },
  {
    id: 19,
    name: "Oliver Smith",
    role: "Engineer",
    email: "oliver.smith@bigbinary.com",
    createdAt: "Feb 5,2021",
  },
  {
    id: 20,
    name: "Oliver Smith",
    role: "Engineer",
    email: "oliver.smith@bigbinary.com",
    createdAt: "Feb 5,2021",
  },
  {
    id: 21,
    name: "Oliver Smith",
    role: "Engineer",
    email: "oliver.smith@bigbinary.com",
    createdAt: "Feb 5,2021",
  },
];
